name: Main workflow

on:
  push:
    branches:
    - source

jobs:
  build:

    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js v16.20.2
      uses: actions/setup-node@v1
      with:
        node-version: '16.20.2'
    - name: prepare build env
      env:
        GH_ACTION_DEPLOY_KEY: ${{ secrets.GH_ACTION_DEPLOY_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$GH_ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.name 'irenhongyan'
        git config --global user.email '2124483716@qq.com'
        npm i -g hexo-cli
        npm i
        git clone -b v1.2.2 git@github.com:blinkfox/hexo-theme-matery.git themes/matery
        cp source/_data/matery.yml themes/matery/_config.yml
    - name: deploy to github 
      run: |
        hexo generate && hexo deploy
